name = "kyc-platform-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kyc-db"
database_id = "48d9f543-7d0a-41c1-8128-e4cfd5063cba"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "kyc-images"
preview_bucket_name = "kyc-images"

[vars]
CORS_ORIGIN = "https://d2302c63.kyc-platform.pages.dev,https://kyc-platform.pages.dev,http://localhost:5173"